/**
 * Top 50 waiting-list names. #1 fixed per PRD (Olivia Yu).
 */
window.__LEADERBOARD__ = [
  { rank: 1, name: "Olivia Yu", note: "#1 Fan · Verified invite" },
  { rank: 2, name: "Amelia Park" },
  { rank: 3, name: "Sofia Reyes" },
  { rank: 4, name: "Hannah Okonkwo" },
  { rank: 5, name: "Valentina Silva" },
  { rank: 6, name: "Maya Thornton" },
  { rank: 7, name: "Elena Petrova" },
  { rank: 8, name: "Nora Williams" },
  { rank: 9, name: "Lily Nakamura" },
  { rank: 10, name: "Gabrielle Moore" },
  { rank: 11, name: "Jasmine Ali" },
  { rank: 12, name: "Rachel Bernstein" },
  { rank: 13, name: "Priya Kapoor" },
  { rank: 14, name: "Chloe Martins" },
  { rank: 15, name: "Vivian Zhou" },
  { rank: 16, name: "Isabella Romano" },
  { rank: 17, name: "Aisha Rahman" },
  { rank: 18, name: "Tessa Brennan" },
  { rank: 19, name: "Mireille Dupont" },
  { rank: 20, name: "Sophie Larsson" },
  { rank: 21, name: "Yuki Taneda" },
  { rank: 22, name: "Grace O’Connor" },
  { rank: 23, name: "Imani Cole" },
  { rank: 24, name: "Laura Nyström" },
  { rank: 25, name: "Nina Kovacs" },
  { rank: 26, name: "Camila Torres" },
  { rank: 27, name: "Helena Kostas" },
  { rank: 28, name: "Keira Singh" },
  { rank: 29, name: "Anouk Fontaine" },
  { rank: 30, name: "Maria Estevez" },
  { rank: 31, name: "Daniella Vogel" },
  { rank: 32, name: "Sienna Brooks" },
  { rank: 33, name: "Felicity Grant" },
  { rank: 34, name: "Rina Morimoto" },
  { rank: 35, name: "Whitney Holt" },
  { rank: 36, name: "Bianca Alvarez" },
  { rank: 37, name: "Katja Lindberg" },
  { rank: 38, name: "Ashley Pemberton" },
  { rank: 39, name: "Monica Delgado" },
  { rank: 40, name: "Naomi Wexler" },
  { rank: 41, name: "Talia Ben-David" },
  { rank: 42, name: "Serena Okada" },
  { rank: 43, name: "Juliana Freitas" },
  { rank: 44, name: "Heather Nguyen" },
  { rank: 45, name: "Leah MacAllister" },
  { rank: 46, name: "Clara van Dijk" },
  { rank: 47, name: "Noor El-Sayed" },
  { rank: 48, name: "Angela Costa" },
  { rank: 49, name: "Renee Washington" },
  { rank: 50, name: "Anika Desai" },
];
